/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#004395",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#8455ef",
        "on-tertiary-container": "#fffbff",
        "on-primary-container": "#fefcff",
        "surface-container-low": "#f2f4f6",
        "surface-tint": "#005ac2",
        "tertiary-fixed": "#e9ddff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary": "#0058be",
        "primary-fixed": "#d8e2ff",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e1e0ff",
        "primary-container": "#2170e4",
        "on-surface": "#191c1e",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c2c6d6",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#001a42",
        "tertiary": "#6b38d4",
        "secondary-container": "#6063ee",
        "on-secondary-fixed": "#07006c",
        "on-tertiary-fixed": "#23005c",
        "error": "#ba1a1a",
        "on-surface-variant": "#424754",
        "background": "#f7f9fb",
        "secondary": "#4648d4",
        "tertiary-fixed-dim": "#d0bcff",
        "inverse-primary": "#adc6ff",
        "surface-container-high": "#e6e8ea",
        "surface": "#f7f9fb",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#5516be",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadc",
        "outline": "#727785",
        "secondary-fixed-dim": "#c0c1ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"
      },
    },
  },
  plugins: [],
};
